---
- name: Install and start PostGreSQL
  hosts: all
  become: true
  tasks:
    - name: Ensure the postgresql-server package is installed
      ansible.builtin.package:
        name: postgresql-server
        state: present
